---

- name: "LOW | RHEL-08-030063 | PATCH | RHEL 8 must resolve audit information before writing to disk."
  when: rhel8stig_030063
  tags:
    - RHEL-08-030063
    - CAT3
    - CCI-000366
    - NIST800-53R4_CM-6
    - SRG-OS-000480-GPOS-00227
    - SV-230395r1017201_rule
    - V-230395
    - auditd
  ansible.builtin.lineinfile:
    path: /etc/audit/auditd.conf
    regexp: '^log_format ='
    line: "log_format = ENRICHED"
  notify: Restart auditd

- name: "LOW | RHEL-08-030601 | PATCH | RHEL 8 must enable auditing of processes that start prior to the audit daemon."
  when: rhel8stig_030601
  tags:
    - RHEL-08-030601
    - CAT3
    - CCI-000169
    - NIST800-53R4_AU-12
    - SRG-OS-000062-GPOS-00031
    - SRG-OS-000037-GPOS-00015
    - SRG-OS-000042-GPOS-00020
    - SRG-OS-000062-GPOS-00031
    - SRG-OS-000392-GPOS-00172
    - SRG-OS-000462-GPOS-00206
    - SRG-OS-000471-GPOS-00215
    - SRG-OS-000473-GPOS-00218
    - SV-230468r1017260_rule
    - V-230468
    - grub
  block:
    - name: "LOW | RHEL-08-030601 | AUDIT | RHEL 8 must enable auditing of processes that start prior to the audit daemon. | Get GRUB_CMDLINE_LINUX settings"
      ansible.builtin.command: grep -i cmdline /etc/default/grub | grep audit=1
      changed_when: false
      failed_when: false
      register: discovered_audit_1_grub_cmdline_linux

    - name: "LOW | RHEL-08-030601 | PATCH | RHEL 8 must enable auditing of processes that start prior to the audit daemon. | Set audit to 1 as active"
      when: discovered_audit_1_grub_cmdline_linux.stdout | length < 1
      ansible.builtin.command: grubby --update-kernel=ALL --args="audit=1"
      changed_when: true
      notify: Rebuild grub

- name: "LOW | RHEL-08-030602 | PATCH | RHEL 8 must allocate an audit_backlog_limit of sufficient size to capture processes that start prior to the audit daemon."
  when: rhel8stig_030602
  tags:
    - RHEL-08-030602
    - CAT3
    - CCI-001849
    - NIST800-53R4_AU-4
    - SRG-OS-000341-GPOS-00132
    - SV-230469r958752_rule
    - V-230469
    - grub
    - auditd
  block:
    - name: "LOW | RHEL-08-030602 | AUDIT | RHEL 8 must allocate an audit_backlog_limit of sufficient size to capture processes that start prior to the audit daemon. | Get GRUB_CMDLINE_LINUX settings"
      ansible.builtin.shell: grep -i cmdline /etc/default/grub | grep audit_backlog_limit=8192
      changed_when: false
      failed_when: false
      register: discovered_audit_backlog_grub_cmdline_linux

    - name: "LOW | RHEL-08-030602 | PATCH | RHEL 8 must allocate an audit_backlog_limit of sufficient size to capture processes that start prior to the audit daemon. | set audit_backlog_limit active"
      when: discovered_audit_backlog_grub_cmdline_linux.stdout | length == 0
      ansible.builtin.command: grubby --update-kernel=ALL --args="audit_backlog_limit=8192"
      changed_when: true
      notify: Rebuild grub

- name: "LOW | RHEL-08-030603 | PATCH | RHEL 8 must enable Linux audit logging for the USBGuard daemon"
  when: rhel8stig_030603
  tags:
    - RHEL-08-030603
    - CAT3
    - CCI-000169
    - NIST800-53R4_AU-12
    - SRG-OS-000062-GPOS-00031
    - SRG-OS-000471-GPOS-00215
    - SV-230470r1017261_rule
    - V-230470
    - usb
  ansible.builtin.lineinfile:
    path: /etc/usbguard/usbguard-daemon.conf
    regexp: '^AuditBackend='
    line: "AuditBackend=LinuxAudit"
    create: true
    owner: root
    group: root
    mode: 'u-x,go-rwx'

- name: "LOW | RHEL-08-030741 | PATCH | RHEL 8 must disable the chrony daemon from acting as a server."
  when:
    - rhel8stig_030741
    - "'chrony' in ansible_facts.packages"
  tags:
    - RHEL-08-030741
    - CAT3
    - CCI-000381
    - NIST800-53R4_CM-7
    - SRG-OS-000095-GPOS-00049
    - SV-230485r1017269_rule
    - V-230485
    - chrony
  ansible.builtin.lineinfile:
    path: /etc/chrony.conf
    regexp: ^#?port
    line: "port 0"

- name: "LOW | RHEL-08-030742 | PATCH | RHEL 8 must disable network management of the chrony daemon."
  when: rhel8stig_030742
  tags:
    - RHEL-08-030742
    - CAT3
    - CCI-000381
    - NIST800-53R4_CM-7
    - SRG-OS-000095-GPOS-00049
    - SV-230486r1017270_rule
    - V-230486
    - chrony
  ansible.builtin.lineinfile:
    path: /etc/chrony.conf
    regexp: ^#?cmdport
    line: "cmdport 0"
