---

- name: Change_requires_reboot
  ansible.builtin.set_fact:
    change_requires_reboot: true

- name: Systemctl daemon-reload
  when: not system_is_container
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart_systemd_login
  ansible.builtin.systemd:
    name: systemd-logind
    state: restarted

- name: Sysctl system
  when: "'procps-ng' in ansible_facts.packages"
  ansible.builtin.command: sysctl --system
  changed_when: true

- name: Restart sshd
  when:
    - not rhel8stig_system_is_chroot
    - "'openssh-server' in ansible_facts.packages"
    - not change_requires_reboot
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: AIDE - Check for DB file
  ansible.builtin.stat:
    path: "{{ rhel8stig_aide_db_file }}"
  register: discovered_aide_db_file
  listen: Build_aide_db

- name: AIDE - Discover age of DB
  when: discovered_aide_db_file.stat.exists
  ansible.builtin.find:
    path: "{{ rhel8stig_aide_db_file | dirname }}"
    pattern: "{{ rhel8stig_aide_db_file | basename }}"
    age: "{{ rhel8stig_aide_db_file_age }}"
  register: discovered_aide_db_age
  listen: Build_aide_db

- name: "AIDE - Create DB if absent, forced or older than {{ rhel8stig_aide_db_file_age }}"
  when: not discovered_aide_db_file.stat.exists or
        (discovered_aide_db_age.files | length > 0) or
        rhel8stig_aide_db_recreate
  ansible.builtin.command: /usr/sbin/aide --init
  changed_when: true
  register: discovered_new_aide_db_created
  listen: Build_aide_db

- name: "AIDE - Rename DB file if DB created"
  when:
    - not discovered_aide_db_file.stat.exists or
      (discovered_aide_db_age.files | length > 0) or
      rhel8stig_aide_db_recreate
    - discovered_new_aide_db_created.changed  # noqa: no-changed-when
  ansible.builtin.command: "mv -f {{ rhel8stig_aide_db_new_file }} {{ rhel8stig_aide_db_file }}"
  changed_when: true
  listen: Build_aide_db

- name: AIDE - If DB exists run check comparison
  when:
    - discovered_aide_db_file.stat.exists
    - not discovered_new_aide_db_created.changed  # noqa: no-changed-when
  ansible.builtin.command: /usr/sbin/aide --check
  changed_when: true
  failed_when: discovered_aidedb_check.rc not in [ 0, 1, 4, 7 ]
  register: discovered_aidedb_check
  listen: Build_aide_db

- name: AIDE - Warning if checks fail
  when: discovered_aidedb_check.rc != 0
  vars:
    warn_control_id: "MEDIUM | RHEL-09-651010-Aide-Check"
  ansible.builtin.import_tasks:
    file: warning_facts.yml
  listen: Build_aide_db

- name: Restart sssd
  when: "'sssd' in ansible_facts.packages"
  ansible.builtin.service:
    name: sssd
    state: restarted

- name: Restart snmpd
  when:
    - not rhel8stig_system_is_chroot
    - not change_requires_reboot
  ansible.builtin.service:
    name: snmpd
    state: restarted

- name: Restart rngd
  when: rhel_08_010471
  ansible.builtin.service:
    name: rngd.service
    state: restarted

- name: Restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted

- name: Restart firewalld
  ansible.builtin.service:
    name: firewalld
    state: restarted

- name: Restart fapolicyd
  ansible.builtin.service:
    name: fapolicyd
    state: restarted

- name: Generate fapolicyd rules
  ansible.builtin.command: fagenrules --load
  changed_when: true

- name: Restart usbguard
  ansible.builtin.service:
    name: usbguard
    state: restarted

- name: Confirm grub2 user cfg
  ansible.builtin.stat:
    path: "/etc/grub.d/01_users"
  changed_when: rhel8stig_grub2_user_cfg.stat.exists
  register: rhel8stig_grub2_user_cfg
  listen: Make grub2 config

- name: Rebuild grub
  when:
    - rhel8stig_grub2_user_cfg.stat.exists
    - not rhel8stig_skip_for_travis
    - not system_is_container
  ansible.builtin.command: /usr/sbin/grub2-mkconfig --output={{ prelim_bootloader_path }}/grub.cfg
  changed_when: true
  listen: Make grub2 config

- name: Copy grub2 config to BIOS/UEFI to satisfy benchmark
  when:
    - rhel8stig_grub2_user_cfg.stat.exists
    - rhel8stig_workaround_for_disa_benchmark
    - not rhel8stig_skip_for_travis
    - not system_is_container
  ansible.builtin.copy:
    src: "{{ prelim_bootloader_path }}/grub.cfg"
    dest: "{{ prelim_bootloader_path }}/grub.cfg"
    remote_src: true
    owner: root
    group: root
    mode: 'u+x,go-w'
  listen: Make grub2 config

- name: "Restart {{ rhel8stig_time_service }}"
  when:
    - not rhel8stig_skip_for_travis
    - not rhel8stig_system_is_chroot
    - not system_is_container
    - not change_requires_reboot
  ansible.builtin.service:
    name: "{{ rhel8stig_time_service }}"
    state: restarted

- name: Update auditd
  ansible.builtin.template:
    src: audit/99_auditd.rules.j2
    dest: /etc/audit/rules.d/99_auditd.rules
    owner: root
    group: root
    mode: 'u-x,go-rwx'
  notify: Restart auditd

- name: Restart auditd  # noqa: command-instead-of-module
  when:
    - not rhel8stig_system_is_chroot
    - not system_is_container
    - not change_requires_reboot
  ansible.builtin.command: /usr/sbin/service auditd restart
  changed_when: true

- name: Rebuild initramfs
  when: not system_is_container
  ansible.builtin.command: dracut -f
  changed_when: true

- name: Undo existing prelinking
  ansible.builtin.command: prelink -ua
  changed_when: true

- name: Update running audit failure mode
  ansible.builtin.command: auditctl -f {{ rhel8stig_auditd_failure_flag }}
  failed_when: false
  changed_when: true

- name: Clean up ssh host key
  with_items:
    - /etc/ssh/ssh_host_rsa_key
    - /etc/ssh/ssh_host_rsa_key.pub
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent

- name: Init aide and wait
  ansible.builtin.command: /usr/sbin/aide --init -B 'database_out=file:{{ rhel8stig_aide_temp_db_file }}'
  changed_when: true
  notify: Move aide db

- name: Init aide
  ansible.builtin.command: nohup /usr/sbin/aide --init -B 'database_out=file:{{ rhel8stig_aide_temp_db_file }}' > /dev/null &
  changed_when: true
  notify: Move aide db

- name: Move aide db
  when: not rhel8stig_aide_db_status.stat.exists or rhel8stig_overwrite_aide_db
  ansible.builtin.command: "mv {{ rhel8stig_aide_temp_db_file }} {{ rhel8stig_aide_db_file }}"
  changed_when: true

- name: Dconf update
  when:
    - "'dconf' in ansible_facts.packages"
    - rhel8stig_always_configure_dconf
  ansible.builtin.command: dconf update
  changed_when: true
